# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydict',
            old_name='des',
            new_name='desc',
        ),
    ]
