# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='课程描述'),
        ),
    ]
