# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('qd', '前端'), ('hd', '后端'), ('qz', '全栈')], default='qd', max_length=10, verbose_name='课程类别'),
        ),
    ]
